name: archivemail
base: core18
adopt-info: archivemail
summary: archive and compress or delete your old email
description: |
  archivemail is a tool for archiving and compressing old email in mailboxes.
  It moves messages older than the specified number of days to a separate mbox
  format mailbox that is compressed with gzip. It can also just delete old
  email rather than archive it.
grade: stable
confinement: strict
architectures:
 - build-on: amd64
   run-on: all
apps:
  archivemail:
    command: archivemail
    plugs: [home]
parts:
  archivemail:
    plugin: nil
    source: git://archivemail.git.sourceforge.net/gitroot/archivemail/archivemail
    build-packages:
    - docbook-xsl
    - make
    - python
    - xsltproc
    stage-packages: [python]
    override-build: |
      snapcraftctl build
      make archivemail.1
      snapcraftctl set-version "$(./setup.py --version)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      cp archivemail $SNAPCRAFT_PART_INSTALL/usr/bin/
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/man/man1
      cp archivemail.1 $SNAPCRAFT_PART_INSTALL/usr/share/man/man1/
